name: CI/CD Pipeline for Flask App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from GitHub repository
    - name: Checkout code
      uses: actions/checkout@v3  # Use v3 to avoid deprecation warnings

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v3  # Use v3 for Python setup
      with:
        python-version: '3.8'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run unit tests
    - name: Run unit tests
      run: |
        python -m unittest discover -s tests

    # Step 5: Deploy to AWS Elastic Beanstalk
    - name: Deploy to AWS Elastic Beanstalk
      if: success()  # Only deploy if all previous steps (tests) are successful
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        EB_ENV_NAME: ${{ secrets.EB_ENV_NAME }}
      run: |
        pip install awsebcli
        eb init -p python-3.8 --region $AWS_REGION
        eb deploy $EB_ENV_NAME
