name: CI/CD Pipeline for Flask App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from GitHub repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    # Step 3: Set up virtual environment
    - name: Set up virtual environment
      run: python -m venv venv

    # Step 4: Activate virtual environment and install dependencies
    - name: Install dependencies
      run: |
        source venv/bin/activate  # Activate the virtual environment
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 5: Run unit tests inside the virtual environment
    - name: Run unit tests
      run: |
        source venv/bin/activate  # Ensure the virtual environment is active
        python -m unittest discover -s tests

   # Step 6: Deploy to Azure App Service
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZUREWEBAPPNAME }}  # Replace with your Azure Web App name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
